export const AUTH = {
  LOGIN: 'LOGIN_SUCCESS',
  REGISTER: 'REGISTER_SUCCESS',
  LOGOUT: 'LOGOUT_SUCCESS',
  FAIL: 'AUTH_FAIL',
  LOADUSER: 'USER_LOADED'
}

export const PROFILE = {
  GET: 'GET_PROFILE',
  ADD: 'PROFILE_ADDED',
  UPDATE: 'PROFILE_UPDATED',
  PROFILE404: 'PROFILE_DOES_NOT_EXIST',
  REVERT404: 'REVERT_PROFILE_404'
};

export const POST = {
  GET: 'GET_POST',
  ADD: 'POST_ADDED',
  LIST: 'GET_POSTLIST',
  USER: {
    ACTIVE: 'GET_USER_ACTIVE_POSTS',
    DISABLED: 'GET_USER_DISABLED_POSTS',
  },
  TOGGLE: 'POST_TOGGLED',
  LIKES: {
    LIKE: 'POST_LIKED',
    DISLIKE: 'POST_DISLIKED',
    REMOVELIKE: 'POST_REMOVE_LIKE',
    REMOVEDISLIKE: 'POST_REMOVE_DISLIKE',
  },
  COMMENT: {
    ADD: 'COMMENT_ADDED',
    LIST: 'GET_COMMENTLIST',
    DISABLE: 'COMMENT_DISABLED',
  },
  CLEAR: {
    USER: 'CLEAR_USER_POST_LIST',
    POST: 'CLEAR_POST_VIEW'
  },
};
